[tool.poetry]
name = "oop-14"
version = "0.1.0"
description = ""
authors = ["Marina <lav_mari@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
